Vialtec/Areas/SuperAdmin/Controllers/DistributorInfosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Datos;
using Utilitarios;
using Logica;
using Vialtec.Models;
using Microsoft.AspNetCore.Authorization;

namespace Vialtec.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = "SuperAdmin")]
    public class DistributorInfosController : Controller
    {
        private readonly VialtecContext _context;
        private LDistributorInfo _logicDistributorInfo;

        public DistributorInfosController(VialtecContext context)
        {
            _context = context;
            _logicDistributorInfo = new LDistributorInfo(context);
        }

        // GET: SuperAdmin/DistributorInfoes
        public async Task<IActionResult> Index(int? pageNumber, string nombre)
        {
            // Número de registros por página
            int pageSize = 10;
            // Almacenará el total de páginas
            int totalPages = 0;

            // ViewDatas de filtro
            ViewData["nombre"] = nombre;

            // Consulta de registros DistributorInfo
            var query = _logicDistributorInfo.All();

            // Filtro nombre
            if (!string.IsNullOrEmpty(nombre))
            {
                query = query.Where(x => x.Title.ToLower().Contains(nombre.ToLower()));
            }

            // Si no hay registros
            if (query.ToList().Count() == 0)
            {
                ViewData["emptyMessage"] = "No se encontraron resultados";
            }
            // Calcular el número de páginas
            decimal result = decimal.Divide(query.ToList().Count(), pageSize);
            // Convierte por ejemplo:  19.3 a 20 páginas
            totalPages = (result - (int)result) != 0 ? (int)result + 1 : (int)result;
            ViewData["totalPages"] = totalPages;

            // Pasar el query de DistributorInfo por el modelo de paginación
            return View(await PaginatedList<DistributorInfo>.CreateAsync(query.AsNoTracking().OrderBy(x => x.Id), pageNumber ?? 1, pageSize));
        }

        // GET: SuperAdmin/DistributorInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> UniqueEmail(string email)
        {
            var distributorInfo = await _logicDistributorInfo.All()
                                        .Where(x => x.Email.ToLower() == email.ToLower())
                                        .FirstOrDefaultAsync();
            return Json(distributorInfo == null); // is unique
        }

        // POST: SuperAdmin/DistributorInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Email,Active,Address,City,Country,ContactPerson")] DistributorInfo distributorInfo)
        {
            if (ModelState.IsValid)
            {
                await _logicDistributorInfo.Create(distributorInfo);
                return RedirectToAction(nameof(Index));
            }
            return View(distributorInfo);
        }

        // GET: SuperAdmin/DistributorInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var distributorInfo = await _logicDistributorInfo.Find(id);
            if (distributorInfo == null)
            {
                return NotFound();
            }
            return View(distributorInfo);
        }

        [HttpGet]
        public async Task<JsonResult> UniqueEmailUpdate(int id, string email)
        {
            var distributorInfo = await _logicDistributorInfo.All()
                                        .Where(x => x.Id != id && x.Email.ToLower() == email.ToLower())
                                        .FirstOrDefaultAsync();
            return Json(distributorInfo == null); // is unique
        }

        // POST: SuperAdmin/DistributorInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Email,Active,Address,City,Country,ContactPerson")] DistributorInfo distributorInfo)
        {
            if (id != distributorInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _logicDistributorInfo.Update(distributorInfo);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DistributorInfoExists(distributorInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(distributorInfo);
        }

        // GET: SuperAdmin/DistributorInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var distributorInfo = await _logicDistributorInfo.All()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (distributorInfo == null)
            {
                return NotFound();
            }

            // ForeignKey validación
            var distributorUsers = _context.DistributorUsers.Where(x => x.DistributorInfoId == id).ToList();
            var customerInfos = _context.CustomerInfos.Where(x => x.DistributorInfoId == id).ToList();

            if (distributorUsers.Count() != 0 || customerInfos.Count() != 0)
            {
                ViewData["foreignKeyMsg"] = "El distribuidor no puede ser eliminado porque está siendo utilizado en otras tablas";
            }

            return View(distributorInfo);
        }

        // POST: SuperAdmin/DistributorInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _logicDistributorInfo.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool DistributorInfoExists(int id)
        {
            return _context.DistributorInfos.Any(e => e.Id == id);
        }
    }
}

Vialtec/Areas/SuperAdmin/Views/DistributorInfos/Create.cshtml
@model Utilitarios.DistributorInfo

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Create" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Nuevo Distriuidor</b>
                </div>
                <div class="card-body row justify-content-center">
                    <div class="col-md-6 col-sm-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label text-muted"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label text-muted"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label text-muted"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="City" class="control-label text-muted"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Country" class="control-label text-muted"></label>
                            <input asp-for="Country" class="form-control" />
                            <span asp-validation-for="Country" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ContactPerson" class="control-label text-muted"></label>
                            <input asp-for="ContactPerson" class="form-control" />
                            <span asp-validation-for="ContactPerson" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group form-check">
                            <label class="form-check-label" style="cursor: pointer;">
                                <input checked class="form-check-input" asp-for="Active" /> <b class="text-muted">Activo</b>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="submit" value="Agregar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function (e) {

            $('#form1').submit((e) => {
                const email = $('#Email').val().trim();
                $.ajax({
                    url: "@Url.Action("UniqueEmail", "DistributorInfos")",
                    data: {
                        email
                    },
                    type: 'get',
                    async: false
                }).done(function (unique) {
                    if (!unique) {
                        Swal.fire({ icon: 'error', title: 'Email', html: `El email <b>${email}</b> ya está siendo utilizado` });
                        $('#Email').val('');
                        e.preventDefault();
                    }
                }).fail(function (error) {
                    console.log(error);
                    e.preventDefault();
                });
            });
        });
    </script>
}

Vialtec/Areas/SuperAdmin/Views/DistributorInfos/Delete.cshtml
@model Utilitarios.DistributorInfo

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
    string display = ViewData["foreignKeyMsg"] != null ? "d-none" : "";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-6 col-sm-8 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <div class="card shadow animate__animated animate__backInDown">
            <div class="card-header">
                <b class="text-muted d-block text-center">¿Estás seguro de eliminar este distribuidor?</b>
            </div>
            <div class="card-body row">
                <div class="col-md-6 col-sm-12">
                    <dl class="dl-horizontal">
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.Title)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Title)
                        </dd>
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.Address)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Address)
                        </dd>
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.Active)
                        </dt>
                        <dd>
                            @*@Html.DisplayFor(model => model.Active)*@
                            @if (Model.Active)
                            {
                                <span class="badge badge-success">Activo</span>
                            }
                            else
                            {
                                <span class="badge badge-warning">Inactivo</span>
                            }
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6 col-sm-12">
                    <dl class="dl-horizontal">
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.City)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.City)
                        </dd>
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.Country)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Country)
                        </dd>
                        <dt class="text-muted">
                            @Html.DisplayNameFor(model => model.ContactPerson)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ContactPerson)
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="card-footer @display">
                <div class="row justify-content-center">
                    <div class="col-md-6 col-sm-8">
                        @*<form asp-action="Delete" id="formDelete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Eliminar" class="btn btn-block btn-outline-danger" />
                        </form>*@
                        <input type="hidden" asp-for="Id" />
                        <input type="button" value="Eliminar" id="btn-eliminar" class="btn btn-block btn-outline-danger" />
                    </div>
                </div>
            </div>
        </div>
        @if (ViewData["foreignKeyMsg"] != null)
        {
            <div class="alert alert-warning animate__animated animate__backInDown">
                <span>@ViewData["foreignKeyMsg"]</span>
            </div>
        }
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function (e) {

            $(document).ajaxStart(function (e) {
                Swal.fire({
                    icon: 'info',
                    title: 'Espere por favor',
                    text: 'Eliminando',
                    allowOutsideClick: false
                });
                Swal.showLoading();
            });
            $(document).ajaxComplete(function (e) {
                Swal.close();
            });

            $('#btn-eliminar').click(function (e) {
                Swal.fire({
                    title: '¿Estás seguro?',
                    text: "No podrás revertir los cambios",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Eliminar',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: "@Url.Action("Delete", "DistributorInfos")",
                            data: $('#Id').val(),
                            type: "post"
                        }).done(function (e) {
                            window.location.href = "@Url.Action("Index", "DistributorInfos")";
                        });
                    }
                })
            });
        });
    </script>
}

Vialtec/Areas/SuperAdmin/Views/DistributorInfos/Edit.cshtml
@model Utilitarios.DistributorInfo

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Edit" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Editar Distriuidor</b>
                </div>
                <div class="card-body row justify-content-center">
                    <div class="col-md-6 col-sm-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="Title" class="control-label text-muted"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label text-muted"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label text-muted"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="City" class="control-label text-muted"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Country" class="control-label text-muted"></label>
                            <input asp-for="Country" class="form-control" />
                            <span asp-validation-for="Country" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ContactPerson" class="control-label text-muted"></label>
                            <input asp-for="ContactPerson" class="form-control" />
                            <span asp-validation-for="ContactPerson" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group form-check">
                            <label class="form-check-label" style="cursor: pointer;">
                                <input class="form-check-input" asp-for="Active" /> <b class="text-muted">Activo</b>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="submit" value="Actualizar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function (e) {
            $('#form1').submit(function (e) {
                const id = $('#Id').val();
                const email = $('#Email').val().trim();
                $.ajax({
                    url: "@Url.Action("UniqueEmailUpdate", "DistributorInfos")",
                    data: {
                        id,
                        email
                    },
                    type: 'get',
                    async: false
                }).done(function (unique) {
                    if (!unique) {
                        e.preventDefault();
                        Swal.fire({ icon: 'error', title: 'Email', html: `El email <b>${email}</b> ya está siendo utilizado` });
                        $('#Email').val('@Model.Email');
                    }
                }).fail(function (error) {
                    console.log(error);
                    e.preventDefault();
                });
            });
        });
    </script>
}

Vialtec/Areas/SuperAdmin/Views/DistributorInfos/Index.cshtml
@model PaginatedList<Utilitarios.DistributorInfo>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
    int totalPages = (int)ViewData["totalPages"];
}

<br />
<h5 class="text-muted d-block text-center" style="font-family: 'Century Gothic';">DISTRIBUIDORES</h5>
<hr />
<div class="row justify-content-center">
    <div class="col-md-10 col-sm-12 table-responsive">
        <div class="row mb-2">
            <div class="col-md-6 col-sm-12 mb-1">
                <a asp-action="Create" class="btn btn-sm btn-info">Agregar&nbsp;&nbsp;<i class="fas fa-plus"></i></a>
                <div class="float-right">
                    <a class="btn btn-sm btn-outline-warning" asp-action="Index" data-toggle="tooltip" title="Deshacer filtros">
                        <i class="fas fa-sync"></i>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <form asp-action="Index" method="get" id="formFilter">
                    <div class="row">
                        <div class="col-6">
                            <input class="form-control form-control-sm" type="text" name="nombre" placeholder="Nombre:" value="@ViewData["nombre"]" />
                        </div>
                        <div class="col-6">
                            <input type="submit" value="Filtrar" class="btn btn-block btn-sm btn-outline-info" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <table class="table table-sm table-bordered mt-2">
            <thead class="thead-dark text-center">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].City)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Country)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].ContactPerson)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model[0].Active)
                    </th>
                    <th colspan="2">Opciones</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.emptyMessage != null)
                {
                    <tr>
                        <td colspan="9" class="text-center">
                            <b class="text-muted">@ViewBag.emptyMessage</b>
                        </td>
                    </tr>
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td class="pl-2">
                            @Html.DisplayFor(modelItem => item.ContactPerson)
                        </td>
                        <td class="text-center">
                            @*@Html.DisplayFor(modelItem => item.Active)*@
                            @if (item.Active)
                            {
                                <span class="badge badge-success">Activo</span>
                            } else
                            {
                                <span class="badge badge-warning">Inactivo</span>
                            }
                        </td>
                        <td class="text-center">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-edit"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="text-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            @if (totalPages > 1)
            {
                <a asp-action="Index"
                   asp-route-nombre="@ViewData["nombre"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   class="btn btn-sm btn-outline-info @prevDisabled">
                    <i class="fas fa-angle-left"></i>
                </a>
                @for (int i = 1; i <= totalPages; i++)
                {
                    string badgeClass = i == Model.PageIndex ? "badge-info" : "badge-light text-muted";
                    <a asp-action="Index"
                       asp-route-nombre="@ViewData["nombre"]"
                       asp-route-pageNumber="@i">
                        <span class="number-page badge @badgeClass" style="transition: 0.5s;">@i</span>
                    </a>
                }
                <a asp-action="Index"
                   asp-route-nombre="@ViewData["nombre"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   class="btn btn-sm btn-outline-info @nextDisabled">
                    <i class="fas fa-angle-right"></i>
                </a>
            }
        </div>
    </div>
</div>
<br />

@section Scripts {
    <script type="text/javascript" src="~/js/navigation.js"></script>
}