Vialtec/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Datos;
using Utilitarios;
using Logica;
using System.Security.Claims;
using Vialtec.Models;
using Microsoft.AspNetCore.Authorization;

namespace Vialtec.Controllers
{
    [Authorize(Roles = "Customer,CustomerAdmin")]
    public class EquipmentsController : Controller
    {
        private readonly VialtecContext _context;
        private readonly LEquipment logicEquipment;

        public EquipmentsController(VialtecContext context)
        {
            _context = context;
            logicEquipment = new LEquipment(context);
        }

        // GET: Equipments
        public async Task<IActionResult> Index(int? pageNumber, int? equipmentGroupId, int? categoryId, int? modelId, string alias, string serial)
        {
            if (!await CheckPermissions())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            // Obtener el customerInfoId de los Claims del login
            int customerInfoId = GetCustomerInfoId();

            // Número de registros por página
            int pageSize = 10;
            // Número de páginas que serán generadas
            int totalPages = 0;

            // ViewBags para los filtros del index
            ViewBag.equipmentGroups = _context.EquipmentGroups.Where(x => x.CustomerInfoId.Equals(customerInfoId)).OrderBy(x => x.Id).ToList();
            ViewBag.categories = _context.Categories.OrderBy(x => x.Id).ToList();
            ViewBag.models = _context.Models.OrderBy(x => x.Id).ToList();

            // ViewDatas para los filtros
            ViewData["equipmentGroupId"] = equipmentGroupId;
            ViewData["categoryId"] = categoryId;
            ViewData["modelId"] = modelId;
            ViewData["alias"] = alias;
            ViewData["serial"] = serial;
            // Obtener el zonetime del cliente para manejar el tema de la última transmissión del equipment
            var customerInfo = await _context.CustomerInfos
                                    .Where(x => x.Id == GetCustomerInfoId())
                                    .FirstOrDefaultAsync();
            ViewData["zoneTime"] = customerInfo.ZoneTime;

            // Consulta de Equipment por customerInfoId
            var query = logicEquipment.All()
                        .Include(e => e.Device).ThenInclude(z => z.Model).ThenInclude(x => x.Category)
                        .Include(e => e.EquipmentGroup)
                        .Where(x => x.EquipmentGroup.CustomerInfoId == customerInfoId);

            // APLICAR FILTROS

            // Filtro de equipmentGroupId
            if (equipmentGroupId != null && equipmentGroupId != -1)
            {
                query = query.Where(x => x.EquipmentGroupId.Equals(equipmentGroupId));
            }

            // Filtro categoryId
            if (categoryId != null && categoryId != -1)
            {
                query = query.Where(x => x.Device.Model.CategoryId.Equals(categoryId));
            }

            // Filtro modelId
            if (modelId != null && modelId != -1)
            {
                query = query.Where(x => x.Device.ModelId.Equals(modelId));
            }

            // Filtro Alias
            if (!string.IsNullOrEmpty(alias))
            {
                query = query.Where(x => x.EquipmentAlias.ToLower().Contains(alias.ToLower()));
            }

            // Filtro Serial
            if (!string.IsNullOrEmpty(serial))
            {
                query = query.Where(x => x.Device.AssetSerial.ToLower().Contains(serial.ToLower()));
            }

            // No hay registros
            if (query.ToList().Count() == 0)
            {
                ViewData["emptyMessage"] = "No se encontraron resultados";
            }
            // Calcular el número de páginas
            decimal result = decimal.Divide(query.ToList().Count(), pageSize);
            // Convierte por ejemplo:  19.3 a 20 páginas
            totalPages = (result - (int)result) != 0 ? (int)result + 1 : (int)result;
            ViewData["totalPages"] = totalPages;

            // Pasamos el query de Equipments por el modelo de paginación
            return View(await PaginatedList<Equipment>.CreateAsync(query.AsNoTracking().OrderBy(x => x.Id), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public async Task<JsonResult> GetEquipmentById(int id)
        {
            var equipment = await logicEquipment.All()
                                .Include(e => e.Device).ThenInclude(x => x.Model).ThenInclude(x => x.Category)
                                .Include(e => e.EquipmentGroup)
                                .FirstOrDefaultAsync(m => m.Id == id);
            var customerInfo = await _context.CustomerInfos.Where(x => x.Id == GetCustomerInfoId())
                                    .FirstOrDefaultAsync();
            TimeSpan span = DateTime.UtcNow.AddHours(customerInfo.ZoneTime).Subtract(equipment.LastDataTx);
            double diffMinutes = span.TotalMinutes;
            return Json(new { equipment, diffMinutes });
        }

        private int GetCustomerInfoId()
        {
            return Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("customerInfoId").Value);
        }

        // GET: Equipments/Create
        public async Task<IActionResult> Create()
        {
            if (!await CheckPermissions())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            var customerInfoId = GetCustomerInfoId();
            var equipmentGroups = _context.EquipmentGroups.Where(x => x.CustomerInfoId == customerInfoId).OrderBy(x => x.Id);
            ViewData["EquipmentGroupId"] = new SelectList(equipmentGroups, "Id", "Title");
            ViewData["categories"] = _context.Categories.OrderBy(x => x.Id).ToList();
            return View();
        }

        /*
         * AJAX
         * Se encarga de retornar los models por una categoría seleccionada
         */
        public JsonResult GetModelsByCategoryId(int categoryId)
        {
            var models = from m in _context.Models
                         where m.CategoryId == categoryId
                         orderby m.Id
                         select m;
            return Json(models);
        }

        /*
         * AJAX
         * Se encarga de retornar los devices por un modelo seleccionado
         */
        public JsonResult GetDevicesByModelId(int modelId)
        {
            // Obtener el customer_info_id de los Claims del login
            int customerInfoId = GetCustomerInfoId();
            // Obtener los Devices que ya fueron asignados anteriormente
            var assignedDevices = _context.Equipments.Include(x => x.Device)
                                   .Select(x => x.Device);
            var devices = _context.Devices
                           .Where(x => x.CustomerInfoId == customerInfoId)
                           .Where(x => x.ModelId == modelId)
                           .OrderBy(x => x.Id);
            // Except para excluir los dispositivos que ya fueron asignados de la consulta
            var data = devices.Except(assignedDevices);
            return Json(data);
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EquipmentAlias,DeviceId,Description,EquipmentGroupId,NotifyInfo")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                await logicEquipment.Create(equipment);
                return RedirectToAction(nameof(Index));
            }
            var customerInfoId = GetCustomerInfoId();
            var equipmentGroups = _context.EquipmentGroups.Where(x => x.CustomerInfoId ==customerInfoId).OrderBy(x => x.Id);
            ViewData["EquipmentGroupId"] = new SelectList(equipmentGroups, "Id", "Title");
            ViewData["categories"] = _context.Categories.OrderBy(x => x.Id).ToList();
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!await CheckPermissions())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await logicEquipment.Find(id);
            if (equipment == null)
            {
                return NotFound();
            }
            var customerInfoId = GetCustomerInfoId();
            var equipmentGroups = _context.EquipmentGroups.Where(x => x.CustomerInfoId == customerInfoId).OrderBy(x => x.Id);
            ViewData["EquipmentGroupId"] = new SelectList(equipmentGroups, "Id", "Title", equipment.EquipmentGroupId);
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EquipmentAlias,Description,EquipmentGroupId,NotifyInfo")] Equipment equipment)
        {
            if (id != equipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Modificar solamente los atributos que se envíaron y mantener los demás como están
                var modelEdit = await logicEquipment.Find(id);

Vialtec/Views/Equipments/Create.cshtml
@model Utilitarios.Equipment

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var categories = ViewData["categories"] as List<Utilitarios.Category>;
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Create" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Nuevo Dispositivo</b>
                </div>
                <div class="card-body">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label class="text-muted">Categoría</label>
                                @{
                                    int inicialID = categories.Count() != 0 ? categories[0].Id : -1;
                                }
                                <select name="categoryId" id="categoryId" class="form-control">
                                    @if (inicialID == -1)
                                    {
                                        <option value="-1"></option>
                                    }
                                    @foreach (var item in categories)
                                    {
                                        <option value="@item.Id">@item.Title</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="text-muted">Modelo</label>
                                <select name="modelId" id="modelId" class="form-control">
                                    @*items dynamic*@
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="text-muted">Dispositivo</label>
                                <select name="deviceId" id="deviceId" class="form-control">
                                    @*items dynamic*@
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="EquipmentGroupId" class="control-label text-muted"></label>
                                <select asp-for="EquipmentGroupId" class="form-control" asp-items="ViewBag.EquipmentGroupId"></select>
                                <span asp-validation-for="EquipmentGroupId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-10">
                            <div class="form-group">
                                <label asp-for="EquipmentAlias" class="control-label text-muted"></label>
                                <input asp-for="EquipmentAlias" class="form-control" />
                                <span asp-validation-for="EquipmentAlias" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="NotifyInfo" class="control-label text-muted"></label>
                                <input asp-for="NotifyInfo" class="form-control" />
                                <span asp-validation-for="NotifyInfo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label text-muted"></label>
                                <textarea rows="4" asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="submit" value="Agregar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script type="text/javascript">
    $(document).ready(function (e) {

            $(document).ajaxStart(function (e) {
                Swal.fire({
                    icon: 'info',
                    title: 'Espere por favor',
                    text: 'Cargando información',
                    allowOutsideClick: false
                });
                Swal.showLoading();
            });

            $(document).ajaxComplete(function (e) {
                Swal.close();
            });

            // ready change models
            loadModels($('#categoryId').val());

            $('#categoryId').change(function (e) {
                var categoryId = $(this).val();
                loadModels(categoryId);
            });

            $('#modelId').change(function (e) {
                var modelId = $(this).val();
                loadDevices(modelId);
            });

            // verificar submit form
            $('#form1').submit(function (e) {
                // verificar categoria, model y device
                if ($('#categoryId').val() == "-1" || $('#modelId').val() == "-1" || $('#deviceId').val() == "-1") {
                    e.preventDefault();
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: 'Debes completar todos los campos'
                    });
                }
            });

            function loadModels(categoryId) {
                $.ajax({
                    url: "@Url.Action("GetModelsByCategoryId", "Equipments")",
                    data: {
                        categoryId
                    },
                    type: "get"
                })
                .done(function (models) {
                    // borrar anteriores option
                    $('#modelId option').remove();
                    models.forEach(x => {
                        let option = `<option value="${x.id}">${x.title}</option>`;
                        $('#modelId').append(option);
                    });
                    if (models.length === 0) {
                        let option = `<option value="-1"></option>`;
                        $('#modelId').append(option);
                        // este modelId no existe entonces no traera nada en los devices
                        loadDevices(-1);
                    } else {
                        // cargar nuevos devices por el primer model id obtenido
                        loadDevices(models[0].id);
                    }
                })
                .fail(function (xhr, status, error) {
                    console.log(error);
                });
            }

            function loadDevices(modelId) {
                $.ajax({
                    url: "@Url.Action("GetDevicesByModelId", "Equipments")",
                    data: {
                        modelId
                    },
                    type: "get"
                })
                .done(function (devices) {
                    console.log(devices);
                    // borrar anteriores option
                    $('#deviceId option').remove();
                    if (devices.length === 0) {
                        let option = `<option value="-1">No hay dispositivos para el modelo</option>`;
                        $('#deviceId').append(option);
                    } else {
                        devices.forEach(x => {
                            let option = `<option value="${x.id}">${x.assetSerial}</option>`;
                            $('#deviceId').append(option);
                        });
                    }
                })
                .fail(function (xhr, status, error) {
                    console.log(error);
                });
            }
        });
</script>
}

Vialtec/Views/Equipments/Delete.cshtml
@model Utilitarios.Equipment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<div class="row justify-content-center">
    <div class="col-md-6 col-sm-8 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <div class="card shadow animate__animated animate__backInDown">
            <div class="card-header">
                <b class="text-muted d-block text-center">¿Estás seguro de eliminar este dispositivo?</b>
            </div>
            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-md-6 col-sm-10">
                        <dl class="dl-horizontal">
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.EquipmentGroup)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.EquipmentGroup.Title)
                            </dd>
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.Device.Model.Category)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Device.Model.Category.Title)
                            </dd>
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.Device.Model)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Device.Model.Title)
                            </dd>
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.NotifyInfo)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.NotifyInfo)
                            </dd>
                        </dl>
                    </div>
                    <div class="col-md-6 col-sm-10">
                        <dl class="dl-horizontal">
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.EquipmentAlias)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.EquipmentAlias)
                            </dd>
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.Description)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Description)
                            </dd>
                            <dt class="text-muted">
                                @Html.DisplayNameFor(model => model.Device.AssetSerial)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Device.AssetSerial)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row justify-content-center">
                    <div class="col-md-6 col-sm-8">
                        <input type="hidden" asp-for="Id" />
                        <input type="button" value="Eliminar" id="btn-eliminar" class="btn btn-block btn-outline-danger" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function (e) {

            $(document).ajaxStart(function (e) {
                Swal.fire({
                    icon: 'info',
                    title: 'Espere por favor',
                    text: 'Eliminando',
                    allowOutsideClick: false
                });
                Swal.showLoading();
            });
            $(document).ajaxComplete(function (e) {
                Swal.close();
            });
            
            $('#btn-eliminar').click(async (e) => {
                const result1 = await mensajeConfirmacion('¿Está seguro de borrarlo?', 'Si elimina el dispositivo, es posible que se pierda la información de reportes asociadas a este equipo');
                if (result1.value) {
                    const result2 = await mensajeConfirmacion('¿Desea continuar?', 'Confirme que desea borrar el dispositivo, esto eliminará la información histórica y geográfica de reportes');
                    if (result2.value) {
                        $.ajax({
                            url: "@Url.Action("Delete", "Equipments")",
                            data: $('#Id').val(),
                            type: "post"
                        }).done(function (e) {
                            window.location.href = "@Url.Action("Index", "Equipments")";
                        });
                    }
                }
            });

            mensajeConfirmacion = (title, text) => {
                return Swal.fire({
                    title,
                    text,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Eliminar',
                    cancelButtonText: 'Cancelar'
                });
            }
        });
    </script>
}

Vialtec/Views/Equipments/Edit.cshtml
@model Utilitarios.Equipment

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Edit" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Editar Dispositivo</b>
                </div>
                <div class="card-body row">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="EquipmentAlias" class="control-label text-muted"></label>
                            <input asp-for="EquipmentAlias" class="form-control" />
                            <span asp-validation-for="EquipmentAlias" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EquipmentGroupId" class="control-label text-muted"></label>
                            <select asp-for="EquipmentGroupId" class="form-control" asp-items="ViewBag.EquipmentGroupId"></select>
                            <span asp-validation-for="EquipmentGroupId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Description" class="control-label text-muted"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NotifyInfo" class="control-label text-muted"></label>
                            <input asp-for="NotifyInfo" class="form-control" />
                            <span asp-validation-for="NotifyInfo" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="submit" value="Actualizar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}