Vialtec/Areas/Admin/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Datos;
using Utilitarios;
using Logica;
using System.Security.Claims;
using Vialtec.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace Vialtec.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DevicesController : Controller
    {
        private readonly VialtecContext _context;
        private readonly LDevice _logicDevice;

        public DevicesController(VialtecContext context)
        {
            _context = context;
            _logicDevice = new LDevice(context);
        }

        // GET: Admin/Devices
        public async Task<IActionResult> Index(int? pageNumber, string serial, int? customerInfoId)
        {
            if (!await AccessGranted())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            // Obtener el distribuor_info_id de los Claims del login
            int distributorInfoId = GetDistributorInfoId();

            // Número de registros por página
            int pageSize = 10;
            // Almacenará el número de páginas
            int totalPages = 0;

            // ViewDatas de filtros
            ViewData["serial"] = serial;
            ViewData["customerInfoId"] = customerInfoId;
            ViewData["customerInfos"] = _context.CustomerInfos.Where(x => x.DistributorInfoId == distributorInfoId).ToList();

            // consulta de registros Devices por customerInfoId
            // La primera consulta trae los Devices pero no trae los que tengan customerInfoId = null
            var query1 = _logicDevice.All().Include(x => x.CustomerInfo).Include(x => x.Model)
                         .Where(x => x.DistributorInfoId == distributorInfoId);
            // La segunda consulta trae los Devices con customerInfoId == null
            var query2 = _logicDevice.All()
                         .Where(x => x.DistributorInfoId == distributorInfoId && x.CustomerInfoId == null);
            // La unión de las dos consultas
            var query = query1.Union(query2);

            // Filtro serial
            if (!string.IsNullOrEmpty(serial))
            {
                query = query.Where(x => x.AssetSerial.Contains(serial));
            }

            // Filtro customerInfoId
            if (customerInfoId != null && customerInfoId != -1)
            {
                query = query.Where(x => x.CustomerInfoId == customerInfoId);
            }

            // Si no hay registros
            if (query.ToList().Count() == 0)
            {
                ViewData["emptyMessage"] = "No se encontraron resultados";
            }
            // Calcular el número de páginas
            decimal result = decimal.Divide(query.ToList().Count(), pageSize);
            // Convierte por ejemplo:  19.3 a 20 páginas
            totalPages = (result - (int)result) != 0 ? (int)result + 1 : (int)result;
            ViewData["totalPages"] = totalPages;

            // Pasar el query Device por el modelo de paginación
            return View(await PaginatedList<Device>.CreateAsync(query.AsNoTracking().OrderBy(x => x.Id), pageNumber ?? 1, pageSize));
        }

        private int GetDistributorInfoId()
        {
            return Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("distributorInfoId").Value);
        }

        // GET: Admin/Devices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!await AccessGranted())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            if (id == null)
            {
                return NotFound();
            }

            var device = await _logicDevice.Find(id);
            if (device == null)
            {
                return NotFound();
            }

            int distributorInfoId = GetDistributorInfoId();
            var customerInfos = _context.CustomerInfos.Where(x => x.DistributorInfoId == distributorInfoId).OrderBy(x => x.Id);
            ViewData["customerInfos"] = customerInfos.ToList();
            return View(device);
        }

        // POST: Admin/Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerInfoId,ZoneTime")] Device device)
        {
            if (id != device.Id)
            {
                return NotFound();
            }
            var currentDevice = await _logicDevice.Find(id);
            try
            {
                currentDevice.CustomerInfoId = device.CustomerInfoId == -1 ? null : device.CustomerInfoId;
                currentDevice.ZoneTime = device.ZoneTime;
                await _logicDevice.Update(currentDevice);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DeviceExists(device.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool DeviceExists(int id)
        {
            return _context.Devices.Any(e => e.Id == id);
        }

        /// <summary>
        /// Se encarga de determinar si el distributorUser autenticado tiene acceso a al controlador/vistas
        /// </summary>
        /// <returns></returns>
        private async Task<bool> AccessGranted()
        {
            string nameController = ControllerContext.ActionDescriptor.ControllerName;
            int distributorUserId = Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("distributorUserId").Value);
            var customerUser = await _context.DistributorUsers
                                .Include(x => x.SecurityProfileDist)
                                .ThenInclude(x => x.ProfilePermissionsDists)
                                .ThenInclude(x => x.SinglePermissionDist)
                                .FirstOrDefaultAsync(x => x.Id == distributorUserId);
            var singlePermissionIdentifiers = customerUser.SecurityProfileDist.ProfilePermissionsDists
                                                .Select(x => x.SinglePermissionDist.Identifier).ToList();
            return singlePermissionIdentifiers.Contains(nameController);
        }
    }
}

Vialtec/Areas/SuperAdmin/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Datos;
using Utilitarios;
using Microsoft.AspNetCore.Authorization;
using Logica;
using Vialtec.Models;

namespace Vialtec.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = "SuperAdmin")]
    public class DevicesController : Controller
    {
        private readonly VialtecContext _context;
        private readonly LDevice _logicDevice;

        public DevicesController(VialtecContext context)
        {
            _context = context;
            _logicDevice = new LDevice(context);
        }

        // GET: SuperAdmin/Devices
        public async Task<IActionResult> Index(int? pageNumber, string serial, int? distributorInfoId)
        {

            // Número de registros por página
            int pageSize = 50;
            // Almacenará el total de páginas
            int totalPages = 0;

            // ViewDatas de filtros
            ViewData["serial"] = serial;
            ViewData["distributorInfoId"] = distributorInfoId;
            ViewData["distributorInfos"] = _context.DistributorInfos.OrderBy(x => x.Id).ToList();

            // La primera consutla regresa lo Devices pero excluye los que tengan customerInfoId = null
            var query1 = _logicDevice.All().Include(x => x.DistributorInfo).Include(x => x.CustomerInfo).Include(x => x.Model);
            // La segunda consulta regresa los Devices donde customerInfoId == null
            var query2 = _logicDevice.All().Include(x => x.DistributorInfo).Include(x => x.Model)
                         .Where(x => x.CustomerInfoId == null);
            // La unión de las dos consultas para obtener todos los registros
            var query = query1.Union(query2);

            // Filtro serial
            if (!string.IsNullOrEmpty(serial))
            {
                query = query.Where(x => x.AssetSerial.Contains(serial));
            }

            // Filtro distributorInfoId
            if (distributorInfoId != null && distributorInfoId != -1)
            {
                query = query.Where(x => x.DistributorInfoId == distributorInfoId);
            }

            // Si no hay registros
            if (query.ToList().Count() == 0)
            {
                ViewData["emptyMessage"] = "No se encontraron resultados";
            }
            // Calcular el número de páginas
            decimal result = decimal.Divide(query.ToList().Count(), pageSize);
            // Convierte por ejemplo:  19.3 a 20 páginas
            totalPages = (result - (int)result) != 0 ? (int)result + 1 : (int)result;
            ViewData["totalPages"] = totalPages;

            // Pasar el query de Devices por el modelo de paginación
            return View(await PaginatedList<Device>.CreateAsync(query.AsNoTracking().OrderBy(x => x.Id), pageNumber ?? 1, pageSize));
        }

        // GET: SuperAdmin/Devices/Create
        public IActionResult Create()
        {
            //ViewData["CustomerInfoId"] = new SelectList(_context.CustomerInfos, "Id", "Title");
            ViewData["DistributorInfoId"] = new SelectList(_context.DistributorInfos.OrderBy(x => x.Id), "Id", "Title");
            ViewData["ModelId"] = new SelectList(_context.Models.OrderBy(x => x.Id), "Id", "Title");
            return View();
        }

        /*
         * Ajax
         * Se encargar de verificar si el AssetSerial que se quiere ingresar existe o no
         */
        [HttpGet]
        public async Task<JsonResult> AssetSerialExists(string assetSerial)
        {
            var device = await _context.Devices
                                .Where(x => x.AssetSerial.ToLower() == assetSerial.ToLower())
                                .FirstOrDefaultAsync();
            return Json(device != null);
        }

        /*
         * Ajax
         * Se encargar de verificar si el NetworkIdentifier que se quiere ingresar existe o no
         */
        [HttpGet]
        public async Task<JsonResult> NetworkIdentifierExists(string networkIdentifier)
        {
            var device = await _context.Devices
                                .Where(x => x.NetworkIdentifier.ToLower() == networkIdentifier.ToLower())
                                .FirstOrDefaultAsync();
            return Json(device != null);
        }

        /*
         * Ajax
         * Se encargar de verificar si el AssetSerial que se quiere ingresar existe o no, teniendo en cuenta que es un update
         */
        [HttpGet]
        public async Task<JsonResult> AssetSerialExistsUpdate(int id, string assetSerial)
        {
            var device = await _context.Devices
                                .Where(x => x.Id != id && x.AssetSerial.ToLower() == assetSerial.ToLower())
                                .FirstOrDefaultAsync();
            return Json(device != null);
        }

        /*
         * Ajax
         * Se encargar de verificar si el NetworkIdentifier que se quiere ingresar existe o no, teniendo en cuenta que es un update
         */
        [HttpGet]
        public async Task<JsonResult> NetworkIdentifierExistsUpdate(int id, string networkIdentifier)
        {
            var device = await _context.Devices
                                .Where(x => x.Id != id && x.NetworkIdentifier.ToLower() == networkIdentifier.ToLower())
                                .FirstOrDefaultAsync();
            return Json(device != null);
        }

        // POST: SuperAdmin/Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AssetSerial,NetworkIdentifier,ModelId,DistributorInfoId,ZoneTime,BluetoothInfo,DevPass")] Device device)
        {
            if (ModelState.IsValid)
            {
                device.CreationDT = DateTime.Now;
                await _logicDevice.Create(device);
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CustomerInfoId"] = new SelectList(_context.CustomerInfos, "Id", "Title", device.CustomerInfoId);
            ViewData["DistributorInfoId"] = new SelectList(_context.DistributorInfos.OrderBy(x => x.Id), "Id", "Title", device.DistributorInfoId);
            ViewData["ModelId"] = new SelectList(_context.Models.OrderBy(x => x.Id), "Id", "Title", device.ModelId);
            return View(device);
        }

        // GET: SuperAdmin/Devices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var device = await _logicDevice.Find(id);
            if (device == null)
            {
                return NotFound();
            }
            //ViewData["CustomerInfoId"] = new SelectList(_context.CustomerInfos, "Id", "Title", device.CustomerInfoId);
            ViewData["DistributorInfoId"] = new SelectList(_context.DistributorInfos.OrderBy(x => x.Id), "Id", "Title", device.DistributorInfoId);
            ViewData["ModelId"] = new SelectList(_context.Models.OrderBy(x => x.Id), "Id", "Title", device.ModelId);
            return View(device);
        }

        // POST: SuperAdmin/Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AssetSerial,NetworkIdentifier,ModelId,CreationDT,CustomerInfoId,DistributorInfoId,ZoneTime,BluetoothInfo,DevPass")] Device device)
        {
            if (id != device.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _logicDevice.Update(device);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CustomerInfoId"] = new SelectList(_context.CustomerInfos, "Id", "Title", device.CustomerInfoId);
            ViewData["DistributorInfoId"] = new SelectList(_context.DistributorInfos.OrderBy(x => x.Id), "Id", "Title", device.DistributorInfoId);
            ViewData["ModelId"] = new SelectList(_context.Models.OrderBy(x => x.Id), "Id", "Title", device.ModelId);
            return View(device);
        }

        // GET: SuperAdmin/Devices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var device = await _logicDevice.All()
                .Include(d => d.CustomerInfo)
                .Include(d => d.DistributorInfo)
                .Include(d => d.Model)
                .FirstOrDefaultAsync(m => m.Id == id);

            // Foreing Keys 
            var equipments = _context.Equipments.Where(x => x.DeviceId == id);
            if (equipments.Count() != 0)
            {
                ViewData["foreignKeyMessage"] = "El dispositivo está siendo utilizado en la tabla { equipments }.";
            }

            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // POST: SuperAdmin/Devices/Delete/5
        [HttpPost, ActionName("Delete")]

Vialtec/Areas/SuperAdmin/Views/Devices/Create.cshtml
@model Utilitarios.Device

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Create" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Nuevo Dispositivo</b>
                </div>
                <div class="card-body row justify-content-center">
                    <div class="col-md-6 col-sm-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="AssetSerial" class="control-label text-muted"></label>
                            <input asp-for="AssetSerial" class="form-control" />
                            <span asp-validation-for="AssetSerial" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ModelId" class="control-label text-muted"></label>
                            <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelId"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="DistributorInfoId" class="control-label text-muted"></label>
                            <select asp-for="DistributorInfoId" class="form-control" asp-items="ViewBag.DistributorInfoId"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="BluetoothInfo" class="control-label text-muted"></label>
                            <input asp-for="BluetoothInfo" class="form-control" />
                            <span asp-validation-for="BluetoothInfo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        @*<div class="form-group">
                            <label asp-for="CustomerInfoId" class="control-label text-muted"></label>
                            <select asp-for="CustomerInfoId" class="form-control" asp-items="ViewBag.CustomerInfoId"></select>
                        </div>*@
                        <div class="form-group">
                            <label asp-for="NetworkIdentifier" class="control-label text-muted"></label>
                            <input asp-for="NetworkIdentifier" class="form-control" />
                            <span asp-validation-for="NetworkIdentifier" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ZoneTime" class="control-label text-muted"></label>
                            <input asp-for="ZoneTime" class="form-control" />
                            <span asp-validation-for="ZoneTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DevPass" class="control-label text-muted"></label>
                            <input asp-for="DevPass" class="form-control" />
                            <span asp-validation-for="DevPass" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="submit" value="Agregar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function (e) {

            $('#form1').submit(function (e) {
                let blueInfo = $('#BluetoothInfo').val();
                if (blueInfo !== '' && !IsJsonString(blueInfo)) {
                    e.preventDefault();
                    Swal.fire({ icon: 'error', text: 'La cadena ingresada para Info Bluetooth no corresponde con un Json válido' });
                }
            });

            $('#BluetoothInfo').blur(function (e) {
                let value = $(this).val();
                if (value !== '' && !IsJsonString(value)) {
                    $(this).val('');
                    Swal.fire({ icon: 'error', text: 'La cadena ingresada para Info Bluetooth no corresponde con un Json válido'});
                }
            });

            function IsJsonString(str) {
                try {
                    JSON.parse(str);
                } catch (e) {
                    return false;
                }
                return true;
            }

            $('#AssetSerial').blur(function (e) {
                $.ajax({
                    url: "@Url.Action("AssetSerialExists", "Devices")",
                    data: {
                        assetSerial: $(this).val()
                    },
                    type: "get"
                }).done(function (exists) {
                    if (exists) {
                        $('#AssetSerial').val('');
                        Swal.fire({ icon: 'error', text: 'El Serial ya está siendo utilizado por otro dispositivo' });
                    }
                }).fail(function (err) { console.log(err); });
            });

            $('#NetworkIdentifier').blur(function (e) {
                $.ajax({
                    url: "@Url.Action("NetworkIdentifierExists", "Devices")",
                    data: {
                        networkIdentifier: $(this).val()
                    },
                    type: "get"
                }).done(function (exists) {
                    if (exists) {
                        $('#NetworkIdentifier').val('');
                        Swal.fire({ icon: 'error', text: 'El Identificador de Red ya está siendo utilizado por otro dispositivo' });
                    }
                }).fail(function (err) { console.log(err); });
            });
        });
    </script>
}

Vialtec/Areas/SuperAdmin/Views/Devices/Edit.cshtml
@model Utilitarios.Device

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/SuperAdmin/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<br />
<div class="row justify-content-center">
    <div class="col-md-8 col-sm-10 col-xs-12">
        <a class="btn btn-sm btn-outline-info animate__animated animate__backInUp" asp-action="Index">
            <i class="fas fa-arrow-left"></i>
        </a>
        <form asp-action="Edit" id="form1">
            <div class="card shadow animate__animated animate__backInDown">
                <div class="card-header">
                    <b class="text-muted d-block text-center">Editar Dispositivo</b>
                </div>
                <div class="card-body row justify-content-center">
                    <div class="col-md-6 col-sm-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="AssetSerial" class="control-label text-muted"></label>
                            <input asp-for="AssetSerial" class="form-control" />
                            <span asp-validation-for="AssetSerial" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ModelId" class="control-label text-muted"></label>
                            <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelId"></select>
                        </div>
                        <div class="form-group">
                            <input type="hidden" value="@Model.DistributorInfoId" id="distributor-info-id-hidden" />
                            <label asp-for="DistributorInfoId" class="control-label text-muted"></label>
                            <select asp-for="DistributorInfoId" class="form-control" asp-items="ViewBag.DistributorInfoId"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="BluetoothInfo" class="control-label text-muted"></label>
                            <input asp-for="BluetoothInfo" class="form-control" />
                            <span asp-validation-for="BluetoothInfo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <input type="hidden" asp-for="CustomerInfoId" />
                        <input type="hidden" asp-for="CreationDT" />
                        <div class="form-group">
                            <label asp-for="NetworkIdentifier" class="control-label text-muted"></label>
                            <input asp-for="NetworkIdentifier" class="form-control" />
                            <span asp-validation-for="NetworkIdentifier" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ZoneTime" class="control-label text-muted"></label>
                            <input asp-for="ZoneTime" class="form-control" />
                            <span asp-validation-for="ZoneTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DevPass" class="control-label text-muted"></label>
                            <input asp-for="DevPass" class="form-control" />
                            <span asp-validation-for="DevPass" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-10">
                            <input type="button" id="btn-submit" value="Actualizar" class="btn btn-block btn-outline-info" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function (e) {

            var id = $('#Id').val();

            $('#btn-submit').click(async function (e) {
                let blueInfo = $('#BluetoothInfo').val();
                if (blueInfo !== '' && !IsJsonString(blueInfo)) {
                    Swal.fire({ icon: 'error', text: 'La cadena ingresada para Info Bluetooth no corresponde con un Json válido' });
                    return;
                }
                // Mensaje de confirmación para reasignar el dispositivo
                const currentDistInfoId = $('#distributor-info-id-hidden').val();
                const newDistInfoId = $('#DistributorInfoId').val();

                if (currentDistInfoId !== newDistInfoId) {
                    const result1 = await mensajeConfirmacion('¿Está seguro de reasignarlo?', 'Si reasigna el dispositivo, es posible que se pierda la información de reportes asociadas a este equipo');
                    if (result1.value) {
                        const result2 = await mensajeConfirmacion('¿Desea continuar?', 'Confirme que desea reasignar el dispositivo, esto eliminará la información histórica y geográfica de reportes');
                        if (result2.value) {
                            $('#form1').submit();
                        }
                    }
                } else {
                    $('#form1').submit();
                }
            });

            mensajeConfirmacion = (title, text) => {
                return Swal.fire({
                    title,
                    text,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    confirmButtonText: 'Reasignar',
                    cancelButtonText: 'Cancelar'
                });
            }

            $('#BluetoothInfo').blur(function (e) {
                let value = $(this).val();
                if (value !== '' && !IsJsonString(value)) {
                    Swal.fire({ icon: 'error', html:  `<b>${$(this).val()}</b> no corresponde a un Json válido para Info bluetooth`});     
                    $(this).val('');
                }
            });

            function IsJsonString(str) {
                try {
                    JSON.parse(str);
                } catch (e) {
                    return false;
                }
                return true;
            }

            $('#AssetSerial').blur(function (e) {
                let assetSerial = $(this).val();
                $.ajax({
                    url: "@Url.Action("AssetSerialExistsUpdate", "Devices")",
                    data: {
                        id,
                        assetSerial
                    },
                    type: "get"
                }).done(function (exists) {
                    if (exists) {
                        $('#AssetSerial').val("@Model.AssetSerial");
                        Swal.fire({ icon: 'error', html: `El Serial <b>${assetSerial}</b> ya está siendo utilizado por otro dispositivo` });
                    }
                }).fail(function (err) { console.log(err); });
            });

            $('#NetworkIdentifier').blur(function (e) {
                let networkIdentifier = $(this).val();
                $.ajax({
                    url: "@Url.Action("NetworkIdentifierExistsUpdate", "Devices")",
                    data: {
                        id,
                        networkIdentifier
                    },
                    type: "get"
                }).done(function (exists) {
                    if (exists) {
                        $('#NetworkIdentifier').val("@Model.NetworkIdentifier");
                        Swal.fire({ icon: 'error', html: `El Identificador de Red <b>${networkIdentifier}</b> ya está siendo utilizado por otro dispositivo` });
                    }
                }).fail(function (err) { console.log(err); });
            });
        });
    </script>
}