Vialtec/Controllers/SendCommandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Datos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Utilitarios;

namespace Vialtec.Controllers
{
    [Authorize(Roles = "Customer,CustomerAdmin")]
    public class SendCommandController : Controller
    {
        private readonly VialtecContext _context;

        public SendCommandController(VialtecContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <returns>View</returns>
        public async Task<IActionResult> Index()
        {
            if (!await CheckPermissions())
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            var equipmentGroups = _context.EquipmentGroups.Where(x => x.CustomerInfoId == GetCustomerInfoId());
            ViewData["EquipmentGroupId"] = new SelectList(equipmentGroups, "Id", "Title");
            return View();
        }

        private int GetCustomerInfoId()
        {
            return Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("customerInfoId").Value);
        }

        private int GetCustomeUserId()
        {
            return Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("customerUserId").Value);
        }

        /// <summary>
        /// Método utilizado para obtener los equipments por equipmentGroup id enviado en la petición AJAX
        /// </summary>
        /// <param name="equipmentGroupId"></param>
        /// <returns>Json de equipments</returns>
        [HttpGet]
        public async Task<JsonResult> GetEquipmentsByEquipmentGroupId(int equipmentGroupId)
        {
            var equipments = _context.Equipments.Where(x => x.EquipmentGroupId == equipmentGroupId);
            return Json(await equipments.ToListAsync());
        }

        /// <summary>
        /// Método utilizado para obtener los precommands para el modelId enviado como parámetros
        /// teniendo en cuenta el nombre personalizado dado por los customerInfo
        /// </summary>
        /// <param name="modelId">Model Id</param>
        /// <returns>Json de precommands</returns>
        [HttpGet]
        public async Task<JsonResult> GetPrecommandsByEquipmentId(int equipmentId)
        {
            // Obtener el modelId del equipment
            int modelId = await _context.Equipments.Include(x => x.Device)
                                .Where(x => x.Id == equipmentId)
                                .Select(x => x.Device.ModelId).FirstOrDefaultAsync();

            // Obtener precomandos con el nombre personalizados filtrando por el cliente y modelo
            var precommandCustomerNames = _context.PrecommandCustomerNames
                                            .Include(x => x.Precommand)
                                            .Where(x => x.CustomerInfoId == GetCustomerInfoId() && x.Precommand.ModelId == modelId);

            #region "USUARIO ADMINISTRADOR"
            // Si el usuario que solicita la información es el usuario administrador, se retornan todos los precommandCustomerNames
            // Sin tener que filtrar por los precommandByUser
            if (User.IsInRole("CustomerAdmin"))
            {
                return Json(await precommandCustomerNames.ToListAsync());
            }
            #endregion

            #region "USUARIO NORMAL"
            // Obtener precomandos también por usuario y modelo
            var precommandByUser = _context.PrecommandByUsers.Include(x => x.Precommand)
                                   .Where(x => x.CustomerUserId == GetCustomeUserId() && x.Precommand.ModelId == modelId);

            // Join entre ambas consultas para obtener los precommandCustomerNames
            var query = from x in precommandCustomerNames
                        join z in precommandByUser on x.PrecommandId equals z.PrecommandId
                        select x;

            return Json(await query.ToListAsync());
            #endregion
        }

        /// <summary>
        /// Almacenar la información del comando
        /// </summary>
        /// <param name="precommandId"></param>
        /// <param name="equipmentId"></param>
        /// <returns>id del comando recien creado o -1 para indicar que ha ocurrido un error</returns>
        [HttpGet]
        public async Task<JsonResult> SaveCommand(int precommandId, int equipmentId)
        {
            var precommand = await _context.Precommands.Where(x => x.Id == precommandId).FirstOrDefaultAsync();
            var equipment = await _context.Equipments.Include(x => x.Device).ThenInclude(x => x.Model)
                                    .Where(x => x.Id == equipmentId).FirstOrDefaultAsync();
            var rnd = new Random();
            string randomNumStr = rnd.Next().ToString();
            var command = new Command
            {
                CustomId = randomNumStr,
                DeviceIdentifier = equipment.Device.NetworkIdentifier,
                CommandData = precommand.CommandData,
                ExpectedAck = precommand.ExpectedAck,
                EncodingTypeId = equipment.Device.Model.EncodingTypeId,
                DeliveryState = 0,
                CreationDT = DateTime.Now,
                ReceivedInfo = string.Empty
            };
            try
            {
                _context.Commands.Add(command);
                await _context.SaveChangesAsync();
                return Json(command.Id);
            }
            catch(Exception)
            {
                return Json(-1);
            }
        }

        /// <summary>
        /// Obtener el objeto Model por el equipmentId seleccionado
        /// </summary>
        /// <param name="equipmentId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<JsonResult>GetModelByEquipmentId(int equipmentId)
        {
            // Encontrar model por equipmentId
            Model model = await _context.Equipments.Include(x => x.Device).ThenInclude(x => x.Model)
                                .Where(x => x.Id == equipmentId)
                                .Select(x => x.Device.Model).FirstOrDefaultAsync();
            return Json(model);
        }

        /// <summary>
        /// Consultar el estado del comando
        /// </summary>
        /// <param name="commandId"></param>
        /// <returns>DeliveryState del comando</returns>
        [HttpGet]
        public async Task<JsonResult> ConsultCommandDeliveryState(int commandId)
        {
            int deliveryState = await _context.Commands.Where(x => x.Id == commandId)
                                       .Select(x => x.DeliveryState).FirstOrDefaultAsync();
            return Json(deliveryState);
        }

        /// <summary>
        /// Verificar si el customer user tiene acceso a las vistas del controlador
        /// </summary>
        /// <returns></returns>
        private async Task<bool> CheckPermissions()
        {
            // Los usuarios administradores tienen permiso a todas las vistas sin verificar permisos de acceso
            if (User.IsInRole("CustomerAdmin")) return true;
            // Obtener customer user id
            int customerUserId = Convert.ToInt32((User.Identity as ClaimsIdentity).FindFirst("customerUserId").Value);
            // Obtener los permisos para el customer user id
            var permissionIdentifiers = await _context.CustomerUserPermissions.Include(x => x.SinglePermission)
                        .Where(x => x.CustomerUserId == customerUserId)
                        .Select(x => x.SinglePermission.Identifier)
                        .ToListAsync();
            return permissionIdentifiers.Contains("GestionRemota");
        }
    }
}

Vialtec/Views/SendCommand/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h5 class="text-muted d-block text-center" style="font-family: 'Century Gothic';">GESTIÓN REMOTA</h5>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <b class="text-muted">Grupos</b>
        <select id="EquipmentGroupId" class="form-control" asp-items="ViewBag.EquipmentGroupId"></select>
        <br/>
        <b class="text-muted">Dispositivos</b>
        <select id="EquipmentId" class="form-control">
            @*equipments*@
        </select>
        <br />
        <b class="text-muted">Comandos</b>
        <div id="precommands" class="text-center">
            @*precommands*@
        </div>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-8 text-center d-none" id="spinner">
        <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="col-8 d-none" id="container-progress">
        <div class="progress">
            <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 0%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
</div>
<br />

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function (e) {

            $(document).ajaxStart(function (e) {
            });

            $(document).ajaxComplete(function (e) {
            });

            // Obtener equipments por equipmentGroupId ------------------
            getEquipments = (equipmentGroupId) => {
                $.ajax({
                    url: "@Url.Action("GetEquipmentsByEquipmentGroupId", "SendCommand")",
                    data: {
                        equipmentGroupId
                    },
                    type: "get"
                }).done(equipments => {
                    showEquipments(equipments);
                }).catch(console.error);
            }

            $('#EquipmentGroupId').change(function (e) {
                getEquipments($(this).val());
            });

            showEquipments = (equipments) => {
                $('#EquipmentId option').remove();
                if (equipments.length == 0) {
                    const optionEmpty = `<option value="-1">No hay dispositivos</option>`;
                    $('#EquipmentId').append(optionEmpty);
                } else {
                    equipments.forEach(equipment => {
                        const option = `<option value="${equipment.id}">${equipment.equipmentAlias}</option>`;
                        $('#EquipmentId').append(option);
                    });
                }
                // Actualizar los precommands también
                getPrecommands($('#EquipmentId').val());
            }
            // -----------------------------------------------------------

            // On change para equipments
            $('#EquipmentId').change(function (e) {
                getPrecommands($(this).val());
            });

            //---- Obtener Precommands por equipmentId -------------------
            getPrecommands = (equipmentId) => {
                $.ajax({
                    url: "@Url.Action("GetPrecommandsByEquipmentId", "SendCommand")",
                    data: {
                        equipmentId
                    },
                    type: "get"
                }).done(precommandCustomerNames => {
                    showPrecommands(precommandCustomerNames);
                }).catch(console.error);
            }

            showPrecommands = (precommandCustomerNames) => {
                $('#precommands .input-group').remove();
                if (precommandCustomerNames.length == 0) {
                    const empty = `
                        <div class="input-group">
                            <input type="text" class="form-control" readonly value="No hay comandos">
                        </div>
                    `;
                    $('#precommands').append(empty);
                } else {
                    precommandCustomerNames.forEach(item => {
                        const option = `
                            <div class="input-group input-group-sm mb-2">
                                <input type="text" class="form-control" readonly
                                    value="${ item.customerTitle }">
                                <div class="input-group-append">
                                    <button type="button" id="${ item.precommand.id }" 
                                        class="btn btn-info btn-precommand">
                                        Enviar
                                    </button>
                                </div>
                            </div>
                        `;
                        $('#precommands').append(option);
                    });
                }
            }
            // ------------------------------------

            // Enviar comando -----------------------------
            $('#precommands').on('click','.btn-precommand', function (e) {
                const precommandId = $(this).attr('id');
                const equipmentId = $('#EquipmentId').val();
                // Almacenar comando
                sendCommand(precommandId, equipmentId);
            });

            sendCommand = (precommandId, equipmentId) => {
                // Deshabilitar buttons
                $('#precommands .btn-precommand').addClass('disabled');
                // Mostrar spinner
                $('#spinner').removeClass('d-none');
                $.ajax({
                    url: "@Url.Action("SaveCommand", "SendCommand")",
                    data: {
                        precommandId,
                        equipmentId
                    },
                    type: "get"
                }).done(commandId => {
                    // Ocultar spinner
                    $('#spinner').addClass('d-none');
                    if (commandId !== -1) {
                        waitDeliveryState(commandId);
                    } else {
                        Swal.fire('Error', 'Ha ocurrido un error', 'error');
                    }
                }).catch(console.error);
            }
            // --------------------------------------------

            // Verificar el DeliveryState ha cambiado valor
            waitDeliveryState = (commandId) => {
                // Mostrar el contenedor de progress-bar
                $('#container-progress').removeClass('d-none');
                let contador = 0;
                let interval = setInterval(async () => {
                    contador += 1;
                    $('.progress-bar').css('width', `${contador * 10}%`);
                    const state = await consultDeliveryState(commandId);
                    console.log({ state });
                    if (state == 3 || contador == 10) {
                        // Terminar intervalo
                        clearInterval(interval);
                        // Habilitar buttons
                        $('#precommands .btn-precommand').removeClass('disabled');
                        // Ocultar contenedor de progress bar
                        $('#container-progress').addClass('d-none');
                        // Reiniciar el porcentaje del progress-bar
                        $('.progress-bar').css('width', '0%');

                        // Mostrar mensaje de éxito o no
                        if (state == 3) {
                            Swal.fire('Enviado', 'El comando se ha enviado exitosamente', 'success');
                        } else {
                            Swal.fire('Advertencia', 'El comando no se ha podido enviar', 'warning');
                        }
                    }
                }, 1000);
            }

            consultDeliveryState = (commandId) => {
                return $.ajax({
                    url: "@Url.Action("ConsultCommandDeliveryState", "SendCommand")",
                    data: { commandId },
                    type: "get"
                });
            }

            // Llamada inicial a los métodos
            getEquipments($('#EquipmentGroupId').val());
            // ---------------------------------------------
        });
    </script>
}